Repository Esri/serlio, pull requests merged in 2022-03, with the labels that each got.

#131 Cknieling/avoid attribute nameclashes
  src/serlio/modifiers/RuleAttributes.cpp
  src/serlio/utils/Utilities.cpp
  src/serlio/utils/Utilities.h
  src/test/tests.cpp
Labels: enhancement

#133 update test framework
  src/common.cmake
  src/test/CMakeLists.txt
  src/test/catch/.clang-format
  src/test/catch/catch.hpp
  src/test/tests.cpp
Labels: enhancement, DevOps

#132 Cknieling/texture cleanup bug
  src/serlio/CMakeLists.txt
  src/serlio/materials/ArnoldMaterialNode.cpp
  src/serlio/materials/ArnoldMaterialNode.h
  src/serlio/materials/MaterialNode.cpp
  src/serlio/materials/MaterialNode.h
  src/serlio/materials/MaterialUtils.cpp
  src/serlio/materials/MaterialUtils.h
  src/serlio/materials/StingrayMaterialNode.cpp
  src/serlio/materials/StingrayMaterialNode.h
Labels: bug
